const sponsorData = [
    {
        // fontpage: false,
        type: 'sponsor',
        ranking: '1',
        index: '1',
        name: 'florana',
        logo: '1',
        description:
            'Pellentesque in ipsum id orci porta dapibus. Quisque velit nisi, pretium ut lacinia in, elementum id enim. Pellentesque in ipsum id orci porta dapibus. Curabitur arcu erat, accumsan id imperdiet et, porttitor at sem.',
        website: 'https://web.com',
        insta: '',
        fb: 'https://web.com',
        twitter: 'https://web.com',
        shareBtn: '',
    },
    {
        type: 'sponsor',
        ranking: '1',
        index: '2',
        name: 'greeen',
        logo: '2',
        description:
            'Sed porttitor lectus nibh. Curabitur arcu erat, accumsan id imperdiet et, porttitor at sem. Mauris blandit aliquet elit, eget tincidunt nibh pulvinar a. Donec sollicitudin molestie malesuada.',
        website: 'https://web.com',
        insta: 'https://web.com',
        fb: '',
        twitter: '',
        shareBtn: '',
    },
    {
        type: 'sponsor',
        ranking: '1',
        index: '3',
        name: 'EcoZoid',
        logo: '3',
        description:
            'Curabitur aliquet quam id dui posuere blandit. Nulla quis lorem ut libero malesuada feugiat. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus. ',
        website: '',
        insta: 'https://web.com',
        fb: 'https://web.com',
        twitter: 'https://web.com',
        shareBtn: '',
    },
    {
        type: 'sponsor',
        ranking: '1',
        index: '4',
        name: 'techic',
        logo: '4',
        description:
            'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec velit neque, auctor sit amet aliquam vel, ullamcorper sit amet ligula.',
        website: 'https://web.com',
        insta: 'https://web.com',
        fb: 'https://web.com',
        twitter: 'https://web.com',
        shareBtn: '',
    },

    // RANKING 2 👇 -- RANKING 2 👇 -- RANKING 2 👇 -- RANKING 2 👇 --
    // RANKING 2 👇 -- RANKING 2 👇 -- RANKING 2 👇 -- RANKING 2 👇 --
    // RANKING 2 👇 -- RANKING 2 👇 -- RANKING 2 👇 -- RANKING 2 👇 --

    {
        type: 'sponsor',
        ranking: '2',
        index: '',
        name: 'solare',
        logo: '5',
        description:
            'Mauris blandit aliquet elit, eget tincidunt nibh pulvinar a. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec velit neque, auctor sit amet aliquam vel, ullamcorper sit amet ligula. Nulla quis lorem ut libero malesuada feugiat. Donec sollicitudin molestie malesuada.',
        website: 'https://web.com',
        insta: 'https://web.com',
        fb: 'https://web.com',
        twitter: 'https://web.com',
        shareBtn: '',
    },
    {
        type: 'sponsor',
        ranking: '2',
        index: '',
        name: 'biocovia',
        logo: '6',
        description:
            'Donec rutrum congue leo eget malesuada. Quisque velit nisi, pretium ut lacinia in, elementum id enim. Curabitur arcu erat, accumsan id imperdiet et, porttitor at sem. Curabitur aliquet quam id dui posuere blandit.',
        website: 'https://web.com',
        insta: 'https://web.com',
        fb: 'https://web.com',
        twitter: 'https://web.com',
        shareBtn: '',
    },
    {
        type: 'sponsor',
        ranking: '2',
        index: '',
        name: 'Sycle',
        logo: '7',
        description:
            'Donec sollicitudin molestie malesuada. Quisque velit nisi, pretium ut lacinia in, elementum id enim. Praesent sapien massa, convallis a pellentesque nec, egestas non nisi. Curabitur arcu erat, accumsan id imperdiet et, porttitor at sem.',
        website: 'https://web.com',
        insta: 'https://web.com',
        fb: 'https://web.com',
        twitter: 'https://web.com',
        shareBtn: '',
    },
    {
        type: 'sponsor',
        ranking: '2',
        index: '',
        name: 'Vegram Eco',
        logo: '8',
        description:
            'Donec sollicitudin molestie malesuada. Quisque velit nisi, pretium ut lacinia in, elementum id enim. Praesent sapien massa, convallis a pellentesque nec, egestas non nisi. Curabitur arcu erat, accumsan id imperdiet et, porttitor at sem.',
        website: 'https://web.com',
        insta: 'https://web.com',
        fb: 'https://web.com',
        twitter: 'https://web.com',
        shareBtn: '',
    },
    {
        type: 'sponsor',
        ranking: '2',
        index: '',
        name: 'solare',
        logo: '9',
        description:
            'Mauris blandit aliquet elit, eget tincidunt nibh pulvinar a. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec velit neque, auctor sit amet aliquam vel, ullamcorper sit amet ligula. Nulla quis lorem ut libero malesuada feugiat. Donec sollicitudin molestie malesuada.',
        website: 'https://web.com',
        insta: 'https://web.com',
        fb: 'https://web.com',
        twitter: 'https://web.com',
        shareBtn: '',
    },
    {
        type: 'sponsor',
        ranking: '2',
        index: '',
        name: 'biocovia',
        logo: '10',
        description:
            'Donec rutrum congue leo eget malesuada. Quisque velit nisi, pretium ut lacinia in, elementum id enim. Curabitur arcu erat, accumsan id imperdiet et, porttitor at sem. Curabitur aliquet quam id dui posuere blandit.',
        website: 'https://web.com',
        insta: 'https://web.com',
        fb: 'https://web.com',
        twitter: 'https://web.com',
        shareBtn: '',
    },
    {
        type: 'sponsor',
        ranking: '2',
        index: '',
        name: 'Sycle',
        logo: '11',
        description:
            'Donec sollicitudin molestie malesuada. Quisque velit nisi, pretium ut lacinia in, elementum id enim. Praesent sapien massa, convallis a pellentesque nec, egestas non nisi. Curabitur arcu erat, accumsan id imperdiet et, porttitor at sem.',
        website: 'https://web.com',
        insta: 'https://web.com',
        fb: 'https://web.com',
        twitter: 'https://web.com',
        shareBtn: '',
    },
    {
        type: 'sponsor',
        ranking: '2',
        index: '',
        name: 'Vegram Eco',
        logo: '12',
        description:
            'Donec sollicitudin molestie malesuada. Quisque velit nisi, pretium ut lacinia in, elementum id enim. Praesent sapien massa, convallis a pellentesque nec, egestas non nisi. Curabitur arcu erat, accumsan id imperdiet et, porttitor at sem.',
        website: 'https://web.com',
        insta: 'https://web.com',
        fb: 'https://web.com',
        twitter: 'https://web.com',
        shareBtn: '',
    },

    {
        type: 'sponsor',
        ranking: '2',
        index: '',
        name: 'solare',
        logo: '13',
        description:
            'Mauris blandit aliquet elit, eget tincidunt nibh pulvinar a. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec velit neque, auctor sit amet aliquam vel, ullamcorper sit amet ligula. Nulla quis lorem ut libero malesuada feugiat. Donec sollicitudin molestie malesuada.',
        website: 'https://web.com',
        insta: 'https://web.com',
        fb: 'https://web.com',
        twitter: 'https://web.com',
        shareBtn: '',
    },
    {
        type: 'sponsor',
        ranking: '2',
        index: '',
        name: 'biocovia',
        logo: '14',
        description:
            'Donec rutrum congue leo eget malesuada. Quisque velit nisi, pretium ut lacinia in, elementum id enim. Curabitur arcu erat, accumsan id imperdiet et, porttitor at sem. Curabitur aliquet quam id dui posuere blandit.',
        website: 'https://web.com',
        insta: 'https://web.com',
        fb: 'https://web.com',
        twitter: 'https://web.com',
        shareBtn: '',
    },
    {
        type: 'sponsor',
        ranking: '2',
        index: '',
        name: 'Sycle',
        logo: '15',
        description:
            'Donec sollicitudin molestie malesuada. Quisque velit nisi, pretium ut lacinia in, elementum id enim. Praesent sapien massa, convallis a pellentesque nec, egestas non nisi. Curabitur arcu erat, accumsan id imperdiet et, porttitor at sem.',
        website: 'https://web.com',
        insta: 'https://web.com',
        fb: 'https://web.com',
        twitter: 'https://web.com',
        shareBtn: '',
    },
    {
        type: 'sponsor',
        ranking: '2',
        index: '',
        name: 'Vegram Eco',
        logo: '16',
        description:
            'Donec sollicitudin molestie malesuada. Quisque velit nisi, pretium ut lacinia in, elementum id enim. Praesent sapien massa, convallis a pellentesque nec, egestas non nisi. Curabitur arcu erat, accumsan id imperdiet et, porttitor at sem.',
        website: 'https://web.com',
        insta: 'https://web.com',
        fb: 'https://web.com',
        twitter: 'https://web.com',
        shareBtn: '',
    },

    // RANKING 3 👇 -- RANKING 3 👇 -- RANKING 3 👇 -- RANKING 3 👇 --
    // RANKING 3 👇 -- RANKING 3 👇 -- RANKING 3 👇 -- RANKING 3 👇 --
    // RANKING 3 👇 -- RANKING 3 👇 -- RANKING 3 👇 -- RANKING 3 👇 --

    {
        type: 'sponsor',
        ranking: '3',
        index: '17',
        name: 'Carian',
        logo: '17',
        description:
            'Vivamus suscipit tortor eget felis porttitor volutpat. Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus. Curabitur arcu erat, accumsan id imperdiet et, porttitor at sem.',
        website: 'https://web.com',
        insta: 'https://web.com',
        fb: 'https://web.com',
        twitter: 'https://web.com',
        shareBtn: '',
    },
    {
        type: 'sponsor',
        ranking: '3',
        index: '18',
        name: 'Marrock',
        logo: '18',
        description:
            'Vivamus suscipit tortor eget felis porttitor volutpat. Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus. Curabitur arcu erat, accumsan id imperdiet et, porttitor at sem.',
        website: 'https://web.com',
        insta: 'https://web.com',
        fb: 'https://web.com',
        twitter: 'https://web.com',
        shareBtn: '',
    },

    {
        type: 'sponsor',
        ranking: '3',
        index: '19',
        name: 'Econfidence',
        logo: '19',
        description:
            'Vivamus suscipit tortor eget felis porttitor volutpat. Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus. Curabitur arcu erat, accumsan id imperdiet et, porttitor at sem.',
        website: 'https://web.com',
        insta: 'https://web.com',
        fb: 'https://web.com',
        twitter: 'https://web.com',
        shareBtn: '',
    },
    {
        type: 'sponsor',
        ranking: '3',
        index: '20',
        name: 'Compower Green',
        logo: '20',
        description:
            'Vivamus suscipit tortor eget felis porttitor volutpat. Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus. Curabitur arcu erat, accumsan id imperdiet et, porttitor at sem.',
        website: 'https://web.com',
        insta: 'https://web.com',
        fb: 'https://web.com',
        twitter: 'https://web.com',
        shareBtn: '',
    },
    {
        type: 'sponsor',
        ranking: '3',
        index: '21',
        name: 'Carbon Realirt',
        logo: '21',
        description:
            'Vivamus suscipit tortor eget felis porttitor volutpat. Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus. Curabitur arcu erat, accumsan id imperdiet et, porttitor at sem.',
        website: 'https://web.com',
        insta: 'https://web.com',
        fb: 'https://web.com',
        twitter: 'https://web.com',
        shareBtn: '',
    },
    {
        type: 'sponsor',
        ranking: '3',
        index: '22',
        name: 'Technate Rechical',
        logo: '22',
        description:
            'Vivamus suscipit tortor eget felis porttitor volutpat. Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus. Curabitur arcu erat, accumsan id imperdiet et, porttitor at sem.',
        website: 'https://web.com',
        insta: 'https://web.com',
        fb: 'https://web.com',
        twitter: 'https://web.com',
        shareBtn: '',
    },

    {
        type: 'sponsor',
        ranking: '3',
        index: '23',
        name: 'SunChant',
        logo: '23',
        description:
            'Vivamus suscipit tortor eget felis porttitor volutpat. Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus. Curabitur arcu erat, accumsan id imperdiet et, porttitor at sem.',
        website: 'https://web.com',
        insta: 'https://web.com',
        fb: 'https://web.com',
        twitter: 'https://web.com',
        shareBtn: '',
    },

    {
        type: 'sponsor',
        ranking: '3',
        index: '24',
        name: 'GreenFlow',
        logo: '24',
        description:
            'Vivamus suscipit tortor eget felis porttitor volutpat. Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus. Curabitur arcu erat, accumsan id imperdiet et, porttitor at sem.',
        website: 'https://web.com',
        insta: 'https://web.com',
        fb: 'https://web.com',
        twitter: 'https://web.com',
        shareBtn: '',
    },
    {
        type: 'sponsor',
        ranking: '3',
        index: '25',
        name: 'Holity Hopes',
        logo: '25',
        description:
            'Vivamus suscipit tortor eget felis porttitor volutpat. Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus. Curabitur arcu erat, accumsan id imperdiet et, porttitor at sem.',
        website: 'https://web.com',
        insta: 'https://web.com',
        fb: 'https://web.com',
        twitter: 'https://web.com',
        shareBtn: '',
    },

    {
        type: 'sponsor',
        ranking: '3',
        index: '26',
        name: 'Colexy Traxel',
        logo: '26',
        description:
            'Vivamus suscipit tortor eget felis porttitor volutpat. Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus. Curabitur arcu erat, accumsan id imperdiet et, porttitor at sem.',
        website: 'https://web.com',
        insta: 'https://web.com',
        fb: 'https://web.com',
        twitter: 'https://web.com',
        shareBtn: '',
    },

    {
        type: 'sponsor',
        ranking: '3',
        index: '27',
        name: 'Carian',
        logo: '27',
        description:
            'Vivamus suscipit tortor eget felis porttitor volutpat. Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus. Curabitur arcu erat, accumsan id imperdiet et, porttitor at sem.',
        website: 'https://web.com',
        insta: 'https://web.com',
        fb: 'https://web.com',
        twitter: 'https://web.com',
        shareBtn: '',
    },
    {
        type: 'sponsor',
        ranking: '3',
        index: '28',
        name: 'Marrock',
        logo: '28',
        description:
            'Vivamus suscipit tortor eget felis porttitor volutpat. Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus. Curabitur arcu erat, accumsan id imperdiet et, porttitor at sem.',
        website: 'https://web.com',
        insta: 'https://web.com',
        fb: 'https://web.com',
        twitter: 'https://web.com',
        shareBtn: '',
    },

    {
        type: 'sponsor',
        ranking: '3',
        index: '29',
        name: 'Econfidence',
        logo: '29',
        description:
            'Vivamus suscipit tortor eget felis porttitor volutpat. Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus. Curabitur arcu erat, accumsan id imperdiet et, porttitor at sem.',
        website: 'https://web.com',
        insta: 'https://web.com',
        fb: 'https://web.com',
        twitter: 'https://web.com',
        shareBtn: '',
    },
    {
        type: 'sponsor',
        ranking: '3',
        index: '30',
        name: 'Compower Green',
        logo: '30',
        description:
            'Vivamus suscipit tortor eget felis porttitor volutpat. Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus. Curabitur arcu erat, accumsan id imperdiet et, porttitor at sem.',
        website: 'https://web.com',
        insta: 'https://web.com',
        fb: 'https://web.com',
        twitter: 'https://web.com',
        shareBtn: '',
    },
    {
        type: 'sponsor',
        ranking: '3',
        index: '31',
        name: 'Carbon Realirt',
        logo: '31',
        description:
            'Vivamus suscipit tortor eget felis porttitor volutpat. Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus. Curabitur arcu erat, accumsan id imperdiet et, porttitor at sem.',
        website: 'https://web.com',
        insta: 'https://web.com',
        fb: 'https://web.com',
        twitter: 'https://web.com',
        shareBtn: '',
    },
    {
        type: 'sponsor',
        ranking: '3',
        index: '32',
        name: 'Technate Rechical',
        logo: '32',
        description:
            'Vivamus suscipit tortor eget felis porttitor volutpat. Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus. Curabitur arcu erat, accumsan id imperdiet et, porttitor at sem.',
        website: 'https://web.com',
        insta: 'https://web.com',
        fb: 'https://web.com',
        twitter: 'https://web.com',
        shareBtn: '',
    },

    {
        type: 'sponsor',
        ranking: '3',
        index: '33',
        name: 'SunChant',
        logo: '33',
        description:
            'Vivamus suscipit tortor eget felis porttitor volutpat. Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus. Curabitur arcu erat, accumsan id imperdiet et, porttitor at sem.',
        website: 'https://web.com',
        insta: 'https://web.com',
        fb: 'https://web.com',
        twitter: 'https://web.com',
        shareBtn: '',
    },

    {
        type: 'sponsor',
        ranking: '3',
        index: '34',
        name: 'GreenFlow',
        logo: '34',
        description:
            'Vivamus suscipit tortor eget felis porttitor volutpat. Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus. Curabitur arcu erat, accumsan id imperdiet et, porttitor at sem.',
        website: 'https://web.com',
        insta: 'https://web.com',
        fb: 'https://web.com',
        twitter: 'https://web.com',
        shareBtn: '',
    },
    {
        type: 'sponsor',
        ranking: '3',
        index: '25',
        name: 'Holity Hopes',
        logo: '25',
        description:
            'Vivamus suscipit tortor eget felis porttitor volutpat. Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus. Curabitur arcu erat, accumsan id imperdiet et, porttitor at sem.',
        website: 'https://web.com',
        insta: 'https://web.com',
        fb: 'https://web.com',
        twitter: 'https://web.com',
        shareBtn: '',
    },

    {
        type: 'sponsor',
        ranking: '3',
        index: '26',
        name: 'Colexy Traxel',
        logo: '26',
        description:
            'Vivamus suscipit tortor eget felis porttitor volutpat. Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus. Curabitur arcu erat, accumsan id imperdiet et, porttitor at sem.',
        website: 'https://web.com',
        insta: 'https://web.com',
        fb: 'https://web.com',
        twitter: 'https://web.com',
        shareBtn: '',
    },
    // {
    //     type: 'sponsor',
    //     ranking: '',
    //     index: '',
    //     name: '',
    //     logo: '',
    //     description: '',
    //     website: 'https://web.com',
    //     insta: 'https://web.com',
    //     fb: 'https://web.com',
    //     twitter: 'https://web.com',
    //     shareBtn: '',
    // },
]

export default sponsorData
